
export const queryKeys = {
  auth: {
    all: ['auth'] as const,
    session: () => [...queryKeys.auth.all, 'session'] as const,
    user: () => [...queryKeys.auth.all, 'user'] as const,
    profile: () => [...queryKeys.auth.all, 'profile'] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    list: (userId: string) => [...queryKeys.notifications.all, userId] as const,
  },
  complaints: {
    all: ['complaints'] as const,
    lists: () => [...queryKeys.complaints.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.complaints.lists(), filters] as const,
    details: () => [...queryKeys.complaints.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.complaints.details(), id] as const,
    stats: (scope: string) => [...queryKeys.complaints.all, 'stats', scope] as const,
  },
  tasks: {
    all: ['tasks'] as const,
    lists: () => [...queryKeys.tasks.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.tasks.lists(), filters] as const,
    details: () => [...queryKeys.tasks.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.tasks.details(), id] as const,
  },
  staff: {
    all: ['staff'] as const,
    lists: () => [...queryKeys.staff.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.staff.lists(), filters] as const,
    details: () => [...queryKeys.staff.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.staff.details(), id] as const,
    performance: (id: string) => [...queryKeys.staff.details(), id, 'performance'] as const,
    attendance: (id: string) => [...queryKeys.staff.details(), id, 'attendance'] as const,
    schedule: (id: string) => [...queryKeys.staff.details(), id, 'schedule'] as const,
    leaves: ['staff', 'leaves'] as const,
  },
  users: {
    all: ['users'] as const,
    lists: () => [...queryKeys.users.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.users.lists(), filters] as const,
    details: () => [...queryKeys.users.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.users.details(), id] as const,
    search: (query: string) => [...queryKeys.users.all, 'search', query] as const,
  },
  payments: {
    all: ['payments'] as const,
    lists: () => [...queryKeys.payments.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.payments.lists(), filters] as const,
    stats: () => [...queryKeys.payments.all, 'stats'] as const,
  },
  notices: {
    all: ['notices'] as const,
    lists: () => [...queryKeys.notices.all, 'list'] as const,
    list: (filters: Record<string, any>) => [...queryKeys.notices.lists(), filters] as const,
  },
  content: {
    all: ['content'] as const,
    pages: () => [...queryKeys.content.all, 'pages'] as const,
    page: (slug: string) => [...queryKeys.content.pages(), slug] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
    admin: () => [...queryKeys.dashboard.all, 'admin'] as const,
    supervisor: () => [...queryKeys.dashboard.all, 'supervisor'] as const,
  },
  lookups: {
    all: ['lookups'] as const,
    wards: () => [...queryKeys.lookups.all, 'wards'] as const,
    departments: () => [...queryKeys.lookups.all, 'departments'] as const,
    categories: () => [...queryKeys.lookups.all, 'categories'] as const,
    roles: () => [...queryKeys.lookups.all, 'roles'] as const,
  },
};
